### ISSUE TITLE
dynamic flags

### ISSUE THREAD

**Issue by stefano055415** [SimonGolms/homekit-code#1]
Hi Simon, is it possible to change the flags of the qr-code?

In order to create a label for BTLE or NFC devices

**Comment by SimonGolms** [comment]
Sounds like a good idea and will check it out in the next few days.

**Comment by stefano055415** [comment]
Hi Simon, thanks for the changes, but there is a problem, it should be possible to select multiple flags at the same time eg IP + WAC

I have try to set the flags to 10 on the code and work fine

**Comment by SimonGolms** [comment]
Hmm, then I probably got that wrong and thanks for the hint! I was under the assumption that there are only the following flags: `IP = 2; BLE = 4; IP_WAC = 8`.
Unfortunately I haven't found any further documentation about this, do you know one?
How do you think the CLI command should look like?

**Comment by stefano055415** [comment]
Hi Simon, I found the correspondence of the flags

NFC = 1, IP = 2, BTLE = 4, WAC = 8

For example, if your device uses both NFC and IP the flag value is NFC + IP = 3

For example, if your device uses both IP and WAC the flag value is IP + WAC = 10

For example, if your device uses both NFC, IP, BTLE and WAC the flag value is NFC + BTLE + IP + WAC = 15

**Comment by SimonGolms** [comment]
Alright, I just released a new version with the changes. Thanks @stefano055415 for the explanation, which I was not familiar with!

**Comment by stefano055415** [comment]
Hi Simon, thanks to you.
The new version works perfectly

**Comment by csprocket777** [comment]
Can you give an example of the usage?
